language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose --all
  - cargo run --example nested_struct
  - cargo run --example simple
  - cargo run --example map
os:
  - windows
  - osx
  - linux