language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - |
    if [[ $TRAVIS_RUST_VERSION == *stable* ]]
    then
      rustup component add rustfmt
      cargo fmt --version
      cargo fmt -- --check || (echo "Please reformat your code with 'cargo fmt' (version $(cargo fmt --version))"; false)
    fi
  - cargo build --verbose --all
  - cargo run --example nested_struct
  - cargo run --example simple
  - cargo run --example map
os:
  - windows
  - osx
  - linux
